name: kaskredit_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0

  # Data Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # UI
  flutter_hooks: ^0.20.4
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  image: ^3.3.0
  network_info_plus: ^5.0.0

  shared_preferences: ^2.2.2

  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  
  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
